name: Processing Image

on:
  workflow_dispatch: 
  push:
    paths:
      - 'images/**/*.jpg'
      - 'images/**/*.JPG'
      - 'images/**/*.png'

jobs:
  process_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"
    - name: Display the path
      run: |
        import os
        print(os.listdir('.'))
      shell: python
    - name: Run image processing script
      run: |
        # Replace this with the command to process your image
        python process_images.py
